---
version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.codeclimate.json

exclude_patterns:
- dist/**/*
- log/**/*
- tmp/**/*
- "**/*.html"
- "**/*.css"
- "**/*.less"
- "**/*.json"
- "**/fonts/**/*"
- "**/images/**/*"
- "**/img/**/*"
- "**/cssimg/**/*"
- shared/lib/**/*
- shared/lib-legacy/**/*
- lib/**/*
- javascripts/**/*
- type/**/*
- node_modules/**/*
- "**/node_modules/**/*"
- asset_list/**/*
- gulp/**/*
