//Guest web template theme file
module.exports = {
	getThemeMappingList : function () {
		var sharedPartials  		 = 'guestweb/**/partials/',
			sharedCommonPartials 	 = 'guestweb/**/partials/**.html',
			landingPartials  		 = 'guestweb/**/landing/partials/',
			checkinPartials      	 = 'guestweb/**/checkin/partials/',
			checkoutNowPartials      = 'guestweb/**/checkoutnow/partials/',
			checkoutNowlaterPartials = 'guestweb/**/checkoutlater/partials/',
			precheckinPartials  	 = 'guestweb/**/preCheckin/partials/',
			sharedHtml  			 = 'guestweb/**/shared/**/*.html';
		return {
			'guestweb_row' 	:[landingPartials + 'Row_nyc/*.html',
							  checkoutNowPartials+'Row_nyc/*.html',checkoutNowPartials+'*.html',
							  checkoutNowlaterPartials+'*.html',
							  checkinPartials+'Row_nyc/*.html',checkinPartials+"*.html",
							  precheckinPartials+'Row_nyc/*.html', precheckinPartials+'*.html',
							  sharedHtml],
			'guestweb_atura' 	:[landingPartials + 'common-black/*.html',
							  checkoutNowPartials+'common-black/*.html',checkoutNowPartials+'*.html',
							  checkoutNowlaterPartials+'*.html',
							  checkinPartials+'common-black/*.html',checkinPartials+"*.html",
							  precheckinPartials+'common-black/*.html', precheckinPartials+'*.html',
							  sharedHtml],
			'guestweb_camby' 	:[ 'guestweb/**/common_hotel_templates/**.html'],
			'guestweb_carillon' 	:[landingPartials + 'Carillon/*.html',
							  checkoutNowPartials+'Carillon/*.html',checkoutNowPartials+'*.html',
							  checkoutNowlaterPartials+'*.html',
							  checkinPartials+'Carillon/*.html',checkinPartials+"*.html",
							  precheckinPartials+'Carillon/*.html', precheckinPartials+'*.html',
							  sharedHtml],
			'guestweb_bellagio' 	:[ 'guestweb/**/mgm_chain/**.html','guestweb/**/mgm_chain/Bellagio/**.html'],
			'guestweb_delano' 	:['guestweb/**/mgm_chain/**.html','guestweb/**/mgm_chain/Delano/**.html'],
			'guestweb_vdara' 	:[ 'guestweb/**/mgm_chain/**.html','guestweb/**/mgm_chain/Vdara/**.html'],
			'guestweb_mandalay_bay':[ 'guestweb/**/mgm_chain/**.html','guestweb/**/mgm_chain/MandalayBay/**.html'],
			'guestweb_envoy' 	 	:[landingPartials + 'Envoy/*.html',
							  checkoutNowPartials+'Envoy/*.html',checkoutNowPartials+'*.html',
							  checkoutNowlaterPartials+'*.html',
							  precheckinPartials+'*.html',
							  sharedHtml],
			'guestweb_eden' 	:[landingPartials + 'Eden_resorts/*.html',
							  checkoutNowPartials+'Eden_resorts/*.html',checkoutNowPartials+'*.html',
							  checkoutNowlaterPartials+'*.html',
							  checkinPartials+'Eden_resorts/*.html',checkinPartials+"*.html",
							  precheckinPartials+'Eden_resorts/*.html', precheckinPartials+'*.html',
							  sharedHtml],
			'guestweb_fulton' 	:[landingPartials + 'Fulton/*.html',
							  checkoutNowPartials+'Fulton/*.html',checkoutNowPartials+'*.html',
							  checkoutNowlaterPartials+'*.html',
							  checkinPartials+'Fulton/*.html',checkinPartials+"*.html",
							  precheckinPartials+'Fulton/*.html', precheckinPartials+'*.html',
							  sharedHtml],
			'guestweb_huntley' 	:[landingPartials + 'Huntley/*.html',
							  checkoutNowPartials+'Huntley/*.html',checkoutNowPartials+'*.html',
							  checkoutNowlaterPartials+'*.html',
							  checkinPartials+'Huntley/*.html',checkinPartials+"*.html",
							  precheckinPartials+'Huntley/*.html', precheckinPartials+'*.html',
							  sharedHtml],
			'guestweb_mgm' 		:[landingPartials + 'MGM/*.html',
								  checkoutNowPartials+'MGM/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'MGM/*.html',
								  checkinPartials+'MGM/*.html',checkinPartials+"*.html",
								  precheckinPartials+'MGM/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_montauk' 	:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_nikko' 	:[landingPartials + 'Nikko/*.html',
								  checkoutNowPartials+'Nikko/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Nikko/*.html',
								  checkinPartials+'Nikko/*.html',checkinPartials+"*.html",
								  precheckinPartials+'NIKKO/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_palms' 	:[landingPartials + 'Palms_spa/*.html',
								  checkoutNowPartials+'Palms_spa/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Palms_spa/*.html',
								  checkinPartials+'Palms_spa/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Palms_spa/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_sanctuary' :[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_yotel' 	:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_zoku' 		:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_fontainebleau' 	:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_great_wolf' 		:[ 'guestweb/**/common_hotel_templates/**.html'],
			'guestweb_knickerbocker' 	:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_margaritaville' 	:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb' 	:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml],
			'guestweb_galleria' 	:[landingPartials + 'Montauk/*.html',
								  checkoutNowPartials+'Montauk/*.html',checkoutNowPartials+'*.html',
								  checkoutNowlaterPartials+'Montauk/*.html',
								  checkinPartials+'Montauk/*.html',checkinPartials+"*.html",
								  precheckinPartials+'Montauk/*.html', precheckinPartials+'*.html',
								  sharedHtml]
		}
	}
}