// ZestStation CSS theme mapping file
module.exports = {
    getThemeMappingList: function() {
        var themeCSSRoot = 'zest_station/css/';

        return {
            'avenue': [themeCSSRoot + 'avenue.less'],
            'sohotel': [themeCSSRoot + 'sohotel.less'],
            'conscious': [themeCSSRoot + 'conscious.less'],
            'zoku': [themeCSSRoot + 'zoku.less'],
            'fontainebleau': [themeCSSRoot + 'fontainebleau.less'],
            'yotel': [themeCSSRoot + 'yotel.less'],
            'epik': [themeCSSRoot + 'epik.less'],
            'public': [themeCSSRoot + 'public.less'],
            'public_v2': [themeCSSRoot + 'public_v2.less'],
            'duke': [themeCSSRoot + 'duke.less'],
            'de-jonker': [themeCSSRoot + 'de-jonker.less'],
            'chalet-view': [themeCSSRoot + 'chalet-view.less'],
            'snt': [themeCSSRoot + 'snt.less'],
            'freehand': [themeCSSRoot + 'freehand.less'],
            'row-nyc': [themeCSSRoot + 'row-nyc.less'],
            'circle-inn-fairfield': [themeCSSRoot + 'circle-inn-fairfield.less'],
            'cachet-boutique': [themeCSSRoot + 'cachet-boutique.less'],
            'hi-ho': [themeCSSRoot + 'hi-ho.less'],
            'first': [themeCSSRoot + 'first.less'],
            'viceroy-chicago': [themeCSSRoot + 'viceroy-chicago.less'],
            'amrath': [themeCSSRoot + 'amrath.less'],
            'jupiter': [themeCSSRoot + 'jupiter.less'],
            'huntley': [themeCSSRoot + 'huntley.less'],
            'queen': [themeCSSRoot + 'queen.less'],
            'belle': [themeCSSRoot + 'belle.less'],
            'freehand-ny': [themeCSSRoot + 'freehand-ny.less'],
            'freehand-miami': [themeCSSRoot + 'freehand-miami.less'],
            'georgetown': [themeCSSRoot + 'georgetown.less'],
            'nomo': [themeCSSRoot + 'nomo.less'],
            'merrill': [themeCSSRoot + 'merrill.less'],
            'martins': [themeCSSRoot + 'martins.less'],
            'arc': [themeCSSRoot + 'arc.less'],
            'alessandra': [themeCSSRoot + 'alessandra.less'],
            'story': [themeCSSRoot + 'story.less'],
            'pod': [themeCSSRoot + 'pod.less'],
            'ihg': [themeCSSRoot + 'ihg.less'],
            'surf-sand': [themeCSSRoot + 'surf-sand.less'],
            'bunk': [themeCSSRoot + 'bunk.less'],
            'rydges': [themeCSSRoot + 'rydges.less'],
            'freehand-la': [themeCSSRoot + 'freehand-la.less'],
            'east-london': [themeCSSRoot + 'east-london.less'],
            'farmers-daughter': [themeCSSRoot + 'farmers-daughter.less'],
            'park-james': [themeCSSRoot + 'park-james.less'],
            'annapolis': [themeCSSRoot + 'annapolis.less'],
            'origin': [themeCSSRoot + 'origin.less'],
            'kinney': [themeCSSRoot + 'kinney.less'],
            'hubert': [themeCSSRoot + 'hubert.less'],
            'de-blend': [themeCSSRoot + 'de-blend.less'],
            'anthony': [themeCSSRoot + 'anthony.less'],
            'stewart': [themeCSSRoot + 'stewart.less'],
            'university-inn': [themeCSSRoot + 'university-inn.less'],
            'cedar-court': [themeCSSRoot + 'cedar-court.less']
        };
    }
};
