//=require ../guestweb/static/lib/js/underscore.min.js
//=require ../guestweb/static/lib/js/less-1.4.1.min.js
//=require ../guestweb/static/lib/js/jquery.js
//=require ../guestweb/static/lib/js/bootstrap.min.js
//=require ../guestweb/static/lib/js/angular.min.js
//=require ../guestweb/static/lib/js/angular-route.js
//=require ../guestweb/static/lib/js/ui-bootstrap-tpls-0.10.0.js
//=require ../guestweb/static/lib/js/angular-ui-router.js
//= require ../guestweb/scripts/Yotel/app.js
//= require ../guestweb/scripts/Yotel/app_router_yotel.js
//= require ../guestweb/scripts/Yotel/app_config.js
//= require_tree ../guestweb/shared
//= require_tree ../guestweb/checkoutlater/controllers/Yotel
//= require_tree ../guestweb/checkoutnow/controllers/Yotel
//= require_tree ../guestweb/checkoutnow/services
//= require_tree ../guestweb/checkoutlater/services
//= require_tree ../guestweb/checkin
