//=require ../staff_housekeeping/lib/js/underscore.min.js
//=require ../staff_housekeeping/lib/js/less-1.4.1.min.js
//=require ../staff_housekeeping/lib/js/angular.min.js
//=require ../staff_housekeeping/lib/js/angular-route.js
//=require ../staff_housekeeping/lib/js/angular-ui-router.js
//=require ../staff_housekeeping/lib/js/angular-animate.js
//=require ../staff_housekeeping/lib/js/ng-iscroll.js
//=require ../staff_housekeeping/js/hkApp.js
//=require_tree ../staff_housekeeping/lib/js
//= require_tree ../staff_housekeeping/js