angular.module('admin').constant("COMTROL_REF", Object.freeze(Object.seal({
    PHONE_CALL_TYPES: [
        {code: 'O', value: 'Operator-assisted'},
        {code: 'M', value: 'Metered Pulses (SMDR)'},
        {code: 'L', value: 'Local'},
        {code: 'I', value: 'Information'},
        {code: 'F', value: "Foreign (Int'l)"},
        {code: 'C', value: 'Credit Card'},
        {code: 'D', value: 'Long Distance'}
    ],
    FOLIO_POSTING_TRANSACTION_CODE: [
        {id: 0, value: 'PMS', code: 'pms'},
        {id: 1, value: 'PBX', code: 'pbx'},
        {id: 2, value: 'Call Accounting', code: 'call_accounting'},
        {id: 3, value: 'In-Room Movies', code: 'in_room_movies'},
        {id: 4, value: 'Keyless Entry', code: 'keyless_entry'},
        {id: 5, value: 'Internet Access', code: 'internet_access'},
        {id: 6, value: 'Interactive Gaming', code: 'interactive_gaming'},
        {id: 7, value: 'In-Room Safe', code: 'in_room_safe'},
        {id: 8, value: 'Point of Sale', code: 'point_of_sale'},
        {id: 9, value: 'Minibar', code: 'minibar'},
        {id: 10, value: 'Voice Mail', code: 'voice_mail'},
        {id: 11, value: 'Tips', code: 'tip_charge_code'}
    ],
    POS_POSTING_CATEGORIES: [
        {id: 0, value: 'General Items', code: 'general_items'},
        {id: 1, value: 'Food', code: 'food'},
        {id: 2, value: 'Beverage', code: 'beverage'},
        {id: 3, value: 'Sales Category 1', code: 'sales_category_1'},
        {id: 4, value: 'Sales Category 2', code: 'sales_category_2'},
        {id: 5, value: 'Sales Category 3', code: 'sales_category_3'},
        {id: 6, value: 'Sales Category 4', code: 'sales_category_4'},
        {id: 7, value: 'Sales Category 5', code: 'sales_category_5'},
        {id: 8, value: 'Sales Category 6', code: 'sales_category_6'},
        {id: 9, value: 'Sales Category 7', code: 'sales_category_7'},
        {id: 10, value: 'Sales Category 8', code: 'sales_category_8'},
        {id: 11, value: 'Non Taxable Sub-Total', code: 'non_taxable_sub_total'},
        {id: 12, value: 'Tax Category 1', code: 'tax_category_1'},
        {id: 13, value: 'Tax Category 2', code: 'tax_category_2'},
        {id: 14, value: 'Tax Category 3', code: 'tax_category_3'},
        {id: 15, value: 'Tax Category 4', code: 'tax_category_4'},
        {id: 16, value: 'Tax Category 5', code: 'tax_category_5'},
        {id: 17, value: 'Tax Category 6', code: 'tax_category_6'},
        {id: 18, value: 'Tax Category 7', code: 'tax_category_7'},
        {id: 19, value: 'Tax Category 8', code: 'tax_category_8'},
        {id: 20, value: 'Service Charge Category 1', code: 'service_charge_category_1'},
        {id: 21, value: 'Service Charge Category 2', code: 'service_charge_category_2'},
        {id: 22, value: 'Service Charge Category 3', code: 'service_charge_category_3'},
        {id: 23, value: 'Service Charge Category 4', code: 'service_charge_category_4'},
        {id: 24, value: 'Service Charge Category 5', code: 'service_charge_category_5'},
        {id: 25, value: 'Service Charge Category 6', code: 'service_charge_category_6'},
        {id: 26, value: 'Service Charge Category 7', code: 'service_charge_category_7'},
        {id: 27, value: 'Service Charge Category 8', code: 'service_charge_category_8'},
        {id: 28, value: 'Service Charge Category 9', code: 'service_charge_category_9'},
        {id: 29, value: 'Service Charge Category 10', code: 'service_charge_category_10'},
        {id: 30, value: 'Discount Category 1', code: 'discount_category_1'},
        {id: 31, value: 'Discount Category 2', code: 'discount_category_2'},
        {id: 32, value: 'Discount Category 3', code: 'discount_category_3'},
        {id: 33, value: 'Discount Category 4', code: 'discount_category_4'},
        {id: 34, value: 'Discount Category 5', code: 'discount_category_5'},
        {id: 35, value: 'Discount Category 6', code: 'discount_category_6'},
        {id: 36, value: 'Discount Category 7', code: 'discount_category_7'},
        {id: 37, value: 'Discount Category 8', code: 'discount_category_8'},
        {id: 38, value: 'Discount Category 9', code: 'discount_category_9'},
        {id: 39, value: 'Discount Category 10', code: 'discount_category_10'},
        {id: 100, value: 'Sales Category 9', code: 'sales_category_9'},
        {id: 101, value: 'Sales Category 10', code: 'sales_category_10'},
        {id: 102, value: 'Sales Category 11', code: 'sales_category_11'},
        {id: 103, value: 'Sales Category 12', code: 'sales_category_12'},
        {id: 104, value: 'Sales Category 13', code: 'sales_category_13'},
        {id: 105, value: 'Sales Category 14', code: 'sales_category_14'},
        {id: 106, value: 'Sales Category 15', code: 'sales_category_15'},
        {id: 107, value: 'Sales Category 16', code: 'sales_category_16'},
        {id: 108, value: 'Sales Category 17', code: 'sales_category_17'},
        {id: 109, value: 'Sales Category 18', code: 'sales_category_18'},
        {id: 110, value: 'Sales Category 19', code: 'sales_category_19'},
        {id: 111, value: 'Sales Category 20', code: 'sales_category_20'},
        {id: 112, value: 'Sales Category 21', code: 'sales_category_21'},
        {id: 113, value: 'Sales Category 22', code: 'sales_category_22'},
        {id: 114, value: 'Sales Category 23', code: 'sales_category_23'},
        {id: 115, value: 'Sales Category 24', code: 'sales_category_24'}
    ],
    ACCESS_LEVELS: [
        {id: 0, value: 'All Allowed'},
        {id: 1, value: 'All Restricted'},
        {id: 2, value: 'Toll Restricted (ECC 1)'},
        {id: 3, value: 'Local Only (ECC 2)'},
        {id: 4, value: 'Internal Only'}
    ]
})));
