// Karma configuration
// Generated on Tue Feb 13 2018 18:35:56 GMT+0530 (IST)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [

        '../shared/lib/js/jquery.min.js',
        '../shared/lib/js/jquery-ui.min.js',
        '../shared/lib/js/jquery.ui.touch-punch.min.js',
        '../shared/lib/js/jquery.qtip.min.js',
        '../shared/lib/js/angular.min.js',
        '../shared/lib/js/angular-mocks.js',
        '../shared/lib/js/angular-route.min.js',
        '../shared/lib/js/angular-ui-router.min.js',
        '../shared/lib/js/angular-animate.min.js',
        '../shared/lib/js/angular-dragdrop.min.js',
        '../shared/lib/js/angular-sanitize.min.js',
        '../shared/lib/js/angular-translate.min.js',
        '../shared/lib/js/angular-translate-loader-static-files.min.js',
        '../shared/lib/js/ui-utils.min.js',
        '../shared/lib/js/underscore.min.js',
        '../shared/lib/js/ngDialog.min.js',
        '../shared/lib/js/spectrum.js',
        '../shared/lib/js/SyntaxHighlighter/shCore.js',
        '../shared/lib/js/SyntaxHighlighter/shBrushXml.js',
        '../shared/lib/js/SyntaxHighlighter/shBrushJScript.js',
        '../shared/lib/js/treeview/ivh-treeview.min.js',
        '../shared/lib/js/moment.min.js',
        '../shared/lib/js/sortable.js',
        '../shared/lib/js/angular-multi-select.js',
        '../shared/lib/js/iscroll.js',
        '../shared/lib/js/ng-iscroll.js',
        '../shared/lib/js/Utils.js',
        '../shared/lib/js/ng-table.js',

        '../shared/interceptors/sharedHttpInterceptor.js',
        '../shared/directives/documentTouchMovePrevent/documentTouchMovePrevent.js',
        '../shared/directives/divTouchMoveStopPropogate/documentTouchMovePrevent.js',
        '../shared/directives/orientationInputBlur/orientationInputBlur.js',
        '../shared/directives/fauxMultiSelect/fauxMutilSelect.js',
        '../shared/directives/eventReachedRoot/eventReachedRoot.js',
        '../shared/directives/ngClassWithoutAnimation/ngClassWithoutAnimation.js',
        '../shared/directives/convertToNumber/convertToNumberDir.js',
        '../shared/directives/tooltip/qtip2.js',

        '../shared/baseCtrl.js',
        '../shared/iBeaconOperations.js',

        '../shared/lib/js/date.js',

        './adRouter/adChainRouter.js',
        './adRouter/adminInterfacesRouter.js',
        './adRouter/adminToolsRouter.js',
        './adRouter/adminZestStationRouter.js',
        './adRouter/adRouterOne.js',
        './adRouter/adRouterTwo.js',


        './adApp.js',
        './adRouter.js',
        './adUtils.js',

        '../rover/rvSntApp.js',

        './controllers/adAccountReceivablesCtrl.js',
        './controllers/adAddCampaignCtrl.js',
        './controllers/adAfasSetupCtrl.js',
        './controllers/adAnalyticSetupCtrl.js',
        './controllers/adAppCtrl.js',
        './controllers/adBaseTableCtrl.js',
        './controllers/adBillingGroupCtrl.js',
        './controllers/adBrandCtrl.js',
        './controllers/adCampaignDatepicker.js',
        './controllers/adCampaignsListCtrl.js',
        './controllers/adChainCtrl.js',
        //'./controllers/adChannelMgrCtrl.js',
        //'./controllers/adChannelMgrEditCtrl.js',
        './controllers/adChargeCodesCtrl.js',
        './controllers/adChargeGroupsCtrl.js',
        './controllers/adCheckinCtrl.js',
        './controllers/ADCheckinEmailCtrl.js',
        './controllers/adCheckoutCtrl.js',
        './controllers/ADCheckoutEmailCtrl.js',
        './controllers/adDailyWorkAssignmentCtrl.js',
        './controllers/adDashboardCtrl.js',
        './controllers/adDateRangeModalCtrl.js',
        './controllers/adDebuggingSetupCtrl.js',
        './controllers/adDepartmentCtrl.js',
        './controllers/addonsDateRangeCtrl.js',
        './controllers/adDoorLockInterfaceCtrl.js',
        './controllers/adEarlyCheckinCtrl.js',
        './controllers/adEmailBlackListCtrl.js',
        //'./controllers/adExternalInterfaceCtrl.js',
        './controllers/adExternalPmsConnectivityCtrl.js',
        './controllers/adFrequentFlyerProgramCtrl.js',
        './controllers/adFTPServersCtrl.js',
        './controllers/adFTPServersDetailsCtrl.js',
        './controllers/adGuestIDSetup.js',
        './controllers/adGuestReviewSetupCtrl.js',
        './controllers/adHoldStatusListCtrl.js',
        './controllers/adHotelCtrl.js',
        './controllers/adHotelDetailsCtrl.js',
        './controllers/adHotelLikeCtrl.js',
        './controllers/adHotelLoyaltyCtrl.js',
        './controllers/adHousekeepingCtrl.js',
        './controllers/adiBeaconDetailsCtrl.js',
        './controllers/adiBeaconSettingsCtrl.js',
        './controllers/adIcareServicesCtrl.js',
        './controllers/adItemDetailsCtrl.js',
        './controllers/adItemListCtrl.js',
        './controllers/adKeyEncoderCtrl.js',
        './controllers/adlinkExistingUserCtrl.js',
        './controllers/ADMaintenanceReasonsCtrl.js',
        './controllers/adMappingCtrl.js',
        './controllers/adMarketsCtrl.js',
        './controllers/adMPSubscriptionPopupCtrl.js',
        './controllers/adOriginsCtrl.js',
        './controllers/adPaymentMethodsCtrl.js',
        './controllers/adPropertyGroupsCtrl.js',
        './controllers/ADPropertyInterfaceSetupCtrl.js',
        './controllers/adRatesActivityLogCtrl.js',
        './controllers/adRatesAddonsCtrl.js',
        './controllers/adRatesListCtrl.js',
        './controllers/ADRatesSequenceCtrl.js',
        './controllers/adRateTypeCtrl.js',
        './controllers/ADReservationSegmentsCtrl.js',
        './controllers/adReservationSettingsCtrl.js',
        './controllers/adReservationTypeListController.js',
        './controllers/adRoomClassesCtrl.js',
        './controllers/adRoomDetailsCtrl.js',
        './controllers/adRoomKeyDeliveryCtrl.js',
        './controllers/adRoomListCtrl.js',
        './controllers/adRoomTypesCtrl.js',
        './controllers/adRoomUpsell.js',
        './controllers/adRulesRestrictionCtrl.js',
        './controllers/adSettingsAndParamsCtrl.js',
        './controllers/adSocialLobbySettingsCtrl.js',
        './controllers/adSourcesCtrl.js',
        './controllers/adStationaryCtrl.js',
        './controllers/adTopCtrl.js',
        './controllers/adUpsellLateCheckoutCtrl.js',
        './controllers/adUserDetailsCtrl.js',
        './controllers/adUserListCtrl.js',
        './controllers/adUserRolePermissions.js',
        './controllers/adUserRolesCtrl.js',
        './controllers/adzestWebGlobalSettingsCtrl.js',
        './controllers/adZestWebPreviewCtrl.js',
        './controllers/booker25/adBooker25SetupCtrl.js',
        './controllers/britePabx/adBritePabXSetupCtrl.js',
        './controllers/chain/ADCertificatesCtrl.js',
        './controllers/clientSuccessManagers/ADClientSuccessManagerDetailsCtrl.js',
        './controllers/clientSuccessManagers/ADClientSuccessManagerListCtrl.js',
        './controllers/contentManagement/adContentManagementAssignComponentCtrl.js',
        './controllers/contentManagement/adContentManagementCategoryDetailCtrl.js',
        './controllers/contentManagement/adContentManagementChildViewCtrl.js',
        './controllers/contentManagement/adContentManagementCtrl.js',
        './controllers/contentManagement/adContentManagementGridViewCtrl.js',
        './controllers/contentManagement/adContentManagementItemDetailCtrl.js',
        './controllers/contentManagement/adContentManagementSectionDetailCtrl.js',
        './controllers/contentManagement/adContentManagementTreeViewCtrl.js',
        './controllers/contentManagement/adDeleteContentCtrl.js',
        './controllers/deviceMapping/adDeviceMappingCtrl.js',
        './controllers/devicesList/adDevicesListCtrl.js',
        './controllers/emvTerminal/adEmvTerminalCtrl.js',
        './controllers/emvTerminal/adEmvTerminalDetailsCtrl.js',
        './controllers/errorPopup/adTimeoutErrorCtrl.js',
        './controllers/ExactOnline/adExactOnlineSetupCtrl.js',
        './controllers/floorSetup/adAssignRoomsCtrl.js',
        './controllers/floorSetup/adFloorDetailsCtrl.js',
        './controllers/floorSetup/adFloorsListCtrl.js',
        './controllers/GustoPOS/adGustoPOSSetupCtrl.js',
        './controllers/hkSections/adAssignRoomsToSectionsCtrl.js',
        './controllers/hkSections/adHKSectionDetailsCtrl.js',
        './controllers/hkSections/adHKSectionListCtrl.js',
        './controllers/IFCComtrol/adIFCComtrolSetupCtrl.js',
        './controllers/interfaces/AccountView/adAccountViewSetupCtrl.js',
        './controllers/interfaces/adInterfaceCommonCtrl.js',
        './controllers/interfaces/ADInterfaceSubMenuCtrl.js',
        './controllers/interfaces/Cendyn/adCendynSetupCtrl.js',
        './controllers/interfaces/Checkmate/adCheckmateSetupCtrl.js',
        './controllers/interfaces/commissions/adOnyxSetupCtrl.js',
        './controllers/interfaces/commissions/adTacsSetupCtrl.js',
        './controllers/interfaces/Comtrol/adComtrolChargeCodeMappingCtrl.js',
        './controllers/interfaces/Comtrol/adComtrolGenericMappingCtrl.js',
        './controllers/interfaces/Comtrol/adComtrolRevenueCenterCtrl.js',
        './controllers/interfaces/Comtrol/adComtrolRoomMappingCtrl.js',
        './controllers/interfaces/CRS/adCRSCommonCtrl.js',
        './controllers/interfaces/Delphi/adDelphiCtrl.js',
        './controllers/interfaces/Digitalalchemy/adDigitalalchemySetupCtrl.js',
        './controllers/interfaces/Duetto/adDuettoSetupCtrl.js',
        './controllers/interfaces/ExternalMappings/ADExternalMappingsAddCtrl.js',
        './controllers/interfaces/ExternalMappings/ADExternalMappingsEditCtrl.js',
        './controllers/interfaces/ExternalMappings/ADExternalMappingsListCtrl.js',
        './controllers/interfaces/GlobalFeatureToggles/adGlobalFeatureTogglesCtrl.js',
        './controllers/interfaces/GoMomentIvy/adGoMomentIvySetupCtrl.js',
        './controllers/interfaces/HotelFeatureToggles/adHotelFeatureTogglesCtrl.js',
        './controllers/interfaces/HotelFeatureToggles/adHotelFeatureTogglesEditCtrl.js',
        './controllers/interfaces/ideas/adIdeasSetupCtrl.js',
        './controllers/interfaces/Keypr/adKeyprSetupCtrl.js',
        './controllers/interfaces/LightSpeed/adLightSpeedProductMapppingCtrl.js',
        './controllers/interfaces/LightSpeed/adLightSpeedRestaurantsCtrl.js',
        './controllers/interfaces/LightSpeed/adSntAdminLightSpeedCredentialSetupCtrl.js',
        './controllers/interfaces/Logs/ADInterfaceLogsCtrl.js',
        './controllers/interfaces/M3BackOffice/ADM3BackOfficeCtrl.js',
        './controllers/interfaces/Monitor/ADInterfaceMonitorCtrl.js',
        './controllers/interfaces/monsciergeSetup/adMonsciergeSetupCtrl.js',
        './controllers/interfaces/Openkey/adOpenkeySetupCtrl.js',
        './controllers/interfaces/Revinate/adRevinateSetupCtrl.js',
        './controllers/interfaces/snapShot/adSnapshotSetupCtrl.js',
        './controllers/interfaces/snapShot/adSnapshotSubGroupMappingCtrl.js',
        './controllers/interfaces/ZDirect/adZDirectSetupCtrl.js',
        './controllers/invoices/adInvoiceSettingsCtrl.js',
        './controllers/languages/adLanguagesCtrl.js',
        './controllers/lightspeedPOS/adLightSpeedPOSSetupCtrl.js',
        './controllers/menuList/adMenuListCtrl.js',
        './controllers/notifications/adNotificationCtrl.js',
        './controllers/notifications/adNotificationsListCtrl.js',
        './controllers/rate_configurator/adAddRateDetailCtrl.js',
        './controllers/rate_configurator/adAddRateRangeCtrl.js',
        './controllers/rate_configurator/adAddRateRoomTypeCtrl.js',
        './controllers/rate_configurator/adEndDatePickerCtrl.js',
        './controllers/rate_configurator/adNewRateCtrl.js',
        './controllers/rate_configurator/adRatesAddConfigureCtrl.js',
        './controllers/rate_configurator/adRatesEndDateValidationPopupCtrl.js',
        './controllers/rates/adPromotionsCtrl.js',
        './controllers/rates/adPromotionsDateRangeCtrl.js',
        './controllers/rates/adRatePromotionsCtrl.js',
        './controllers/reports/ADReportsListCtrl.js',
        './controllers/reports/clientUsageReport/ADClientUsageReportFilterCtrl.js',
        './controllers/reservationTools/adBalanceInventoryCtrl.js',
        './controllers/reservationTools/adBalanceJournalCtrl.js',
        './controllers/reservationTools/AdJobDatePickerBalanceJournalCtrl.js',
        './controllers/reservationTools/adJobDatePickerCtrl.js',
        './controllers/reservationTools/adReservationToolsMainCtrl.js',
        './controllers/reservationTools/adResyncRatesCtrl.js',
        './controllers/serviceProviders/adServiceProviderCtrl.js',
        './controllers/serviceProviders/adServiceProviderDetailsCtrl.js',
        './controllers/serviceProviders/adServiceProviderUserDetailsCtrl.js',
        './controllers/serviceProviders/adServiceProviderUsersListCtrl.js',
        './controllers/smsConfiguration/ADSMSConfigurationCtrl.js',
        './controllers/sntApps/adSntAppsListCtrl.js',
        './controllers/stationary/adStationaryTermsAndConditionsCtrl.js',
        './controllers/templateConfiguration/adTemplateConfigurationCtrl.js',
        './controllers/tools/adToolsCtrl.js',
        './controllers/tools/TelnetInterface/adTelnetInterfaceCtrl.js',
        './controllers/translation/adTranslationCtrl.js',
        './controllers/upsellAdons/adUpsellAddonSettingsCtrl.js',
        './controllers/webhook/ADWebhookListCtrl.js',
        './controllers/zestEmailTemplates/adZestBaseEmailSettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestCheckinEmailSettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestCheckoutEmailSettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestEmailGeneralSettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestEmailMenuCtrl.js',
        './controllers/zestEmailTemplates/adZestKeyDeliveryCommonCtrl.js',
        './controllers/zestEmailTemplates/adZestLateCheckoutEmailSettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestMobileKeyEmailSettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestPrecheckinEmailSettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestQRKeyDeliverySettingsCtrl.js',
        './controllers/zestEmailTemplates/adZestTextKeyDeliverySettingsCtrl.js',
        './controllers/zestSetup/adCountrySortCtrl.js',
        './controllers/zestSetup/adSortableAddonListBaseCtrl.js',
        './controllers/zestSetup/ADZestCheckinDirectUrlEmailCtrl.js',
        './controllers/zestSetup/ADZestCheckinEmailCtrl.js',
        './controllers/zestSetup/adZestMobileAppMarketingCtrl.js',
        './controllers/zestSetup/ADZestSmsShortcodeCtrl.js',
        './controllers/zestSetup/adZestStationLanguageConfigCtrl.js',
        './controllers/zestSetup/adZestWebAddonCtrl.js',
        './controllers/zestSetup/adZestWebRoomReadyEmailSetupCtrl.js',
        './controllers/zestStation/adZestStationAddonCtrl.js',
        './controllers/zestStation/adZestStationCheckInCtrl.js',
        './controllers/zestStation/adZestStationCheckOutCtrl.js',
        './controllers/zestStation/adZestStationCtrl.js',
        './controllers/zestStation/adZestStationHueSettingsCtrl.js',
        './controllers/zestStation/adZestStationMobilePhoneKeyEmailSetupCtrl.js',
        './controllers/zestStation/adZestStationPickUpKeysCtrl.js',
        './controllers/zestStation/adZestStationRoomUpsellCtrl.js',
        './controllers/zestwebCommon/adZestwebCommonSettingsCtrl.js',

        './directives/adminCommonPartsInForm/adCommonPartsInFormDir.js',
        './directives/adSelectNumber/adSelectNumberDir.js',
        './directives/adSyncBlock/adSyncBlockCtrl.js',
        './directives/adSyncBlock/adSyncBlockDir.js',
        './directives/autocomplete/autocomplete.js',
        './directives/chargeCodeAutoComplete/adChargeCodeAutoCompleteDir.js',
        './directives/chargeCodeSearch/chargeCodeSearchDir.js',
        './directives/checkBox/adCheckboxDir.js',
        './directives/checkBox/adCheckboxGroupDir.js',
        './directives/checkBox/adCheckboxLeftTextDir.js',
        './directives/delayTextbox/adDelayTextBox.js',
        './directives/enterKeyPress.js',
        './directives/fauxSelect/fauxSelectDir.js',
        './directives/fileRead/adFileread.js',
        './directives/filterTable/adFilterTable.js',
        './directives/filterTable/adFilterTableCtrl.js',
        './directives/focusMe/adDocusMeDir.js',
        './directives/FormHeaderWithBackButton/adFormHeaderWithBackButtonDir.js',
        './directives/FormSubTitle/adFormSubTitleDir.js',
        './directives/FormTitle/adFormTitleDir.js',
        './directives/includeReplaceDir.js',
        './directives/jsonText/jsonTextDir.js',
        './directives/numberListing.js',
        './directives/Outside Click handler/adminOutsideClickDirective.js',
        './directives/radio/adRadioDir.js',
        './directives/SaveCancelArea/adSaveCancelAreaDir.js',
        './directives/scrollup.js',
        './directives/selectBox/adDropdownboxDir.js',
        './directives/selectBox/adDropdownboxDirName.js',
        './directives/selectBox/adMultiselectboxDir.js',
        './directives/SyntaxHighlighter/highlightSyntaxDir.js',
        './directives/textArea/adTextAreaDir.js',
        './directives/textBox/adTextboxDir.js',
        './directives/TimeSelector/ADTimeSelectorDir.js',
        './directives/toggle/adToggleButtonDir.js',
        './directives/TreeSelectorCheckBox/ADTreeSelectorCheckBoxDir.js',

        './services/adAccountReceivablesSrv.js',
        './services/adAfasSetupSrv.js',
        './services/adAnalyticSetupSrv.js',
        './services/adAppSrv.js',
        './services/adBaseWebSrv.js',
        './services/adBaseWebSrvV2.js',
        './services/adBillingGroupSrv.js',
        './services/adBrandsSrv.js',
        './services/adCampaignSrv.js',
        './services/adChainsSrv.js',
        './services/adChannelMgrSrv.js',
        './services/adChargeCodesSrv.js',
        './services/adChargeGroupsSrv.js',
        './services/adCheckinCheckoutSrv.js',
        './services/adCheckinSrv.js',
        './services/adCheckoutSrv.js',
        './services/ADClientSuccessManagerSrv.js',
        './services/adContentManagementSrv.js',
        './services/adDailyWorkAssignmentSrv.js',
        './services/adDashboardSrv.js',
        './services/adDebuggingSetupSrv.js',
        './services/adDepartmentSrv.js',
        './services/adDoorlockInterfaceSrv.js',
        './services/adEmailBlackListSrv.js',
        './services/adEmailSettings/adCheckinEmailRoomFilterSrv.js',
        './services/adEmailSettings/adCheckoutEmailRoomFilterSrv.js',
        './services/adExternalInterfaceCommonSrv.js',
        './services/adExternalPmsConnectivitySrv.js',
        './services/adFrequentFlyerProgramSrv.js',
        './services/adFTPServersSrv.js',
        './services/adGivexSetupSrv.js',
        './services/adGuestIDSetupSrv.js',
        './services/adGuestReviewSetupSrv.js',
        './services/ADHoldStatusSrv.js',
        './services/adHotelConfiguration/adHotelConfigurationSrv.js',
        './services/adHotelDetailsSrv.js',
        './services/adHotelLikesSrv.js',
        './services/adHotelListSrv.js',
        './services/adHotelLoyaltySrv.js',
        './services/adHotelPropertyInterfaces/ADHotelPropertyInterfaceSrv.js',
        './services/adHotelSettingsSrv.js',
        './services/adIbeaconSettingsService.js',
        './services/adIcareServicesSrv.js',
        './services/adInvoiceSettingsSrv.js',
        './services/adItemSrv.js',
        './services/adKeyEncoderSrv.js',
        './services/ADMaintenanceReasonsSrv.js',
        './services/adMarketsSrv.js',
        './services/adMultiPropertyUserSettingsSrv.js',
        './services/adOriginsSrv.js',
        './services/adPaymentMethodsSrv.js',
        './services/adPropertyGroupsSrv.js',
        './services/adRateActivityLogSrv.js',
        './services/adRatesAddonsSrv.js',
        './services/ADRateSequenceSrv.js',
        './services/adRatesSrv.js',
        './services/adRateTypeSrv.js',
        './services/adReservationSettingsSrv.js',
        './services/adReservationToolsSrv.js',
        './services/adReservationTypesSrv.js',
        './services/adRoomClassesSrv.js',
        './services/adRoomKeyDeliverySrv.js',
        './services/adRoomSrv.js',
        './services/adRoomTypesSrv.js',
        './services/adRoomUpsellSrv.js',
        './services/adRulesRestrictionSrv.js',
        './services/adSegmentsSrv.js',
        './services/adSettingsAndParamsSrv.js',
        './services/adSiteminderSetupSrv.js',
        './services/adSocialLobbySrv.js',
        './services/adSourcesSrv.js',
        './services/adStationarySrv.js',
        './services/adSynxisSetupSrv.js',
        './services/adTravelTripperSetupSrv.js',
        './services/adUpsellEarlyCheckinService.js',
        './services/adUpsellLatecheckoutService.js',
        './services/adUserRolePermissionSrv.js',
        './services/adUserRolesSrv.js',
        './services/adUserSrv.js',
        './services/adZDirectSetupSrv.js',
        './services/adZestShortCodeSrv.js',
        './services/adZestStationSrv.js',
        './services/adZestwebCommon/adzestwebCommonSettingsSrv.js',
        './services/adzestWebGlobalSettingsSrv.js',
        './services/booker25/adBooker25SetupSrv.js',
        './services/chain/ADCertificatesSrv.js',
        './services/deviceMapping/adDeviceSrv.js',
        './services/emvTerminalList/adEmvTerminalsSrv.js',
        './services/ExactOnLine/adExactOnlineSetupSrv.js',
        './services/floorSetup/adFloorSetupSrv.js',
        './services/GustoPOS/adGustoPOSSetupSrv.js',
        './services/hkSections/adHouseKeepingSectionSrv.js',
        './services/IFCComtrol/adIFCComtrolSetupSrv.js',
        //'./services/interfaceMapping/adInterfaceMappingSrv.js',
        './services/interfaces/adFeaturesSrv.js',
        './services/interfaces/adInterfacesCommonConfigSrv.js',
        './services/interfaces/Checkmate/adCheckmateSrv.js',
        './services/interfaces/commissions/adCommissionsConfigSrv.js',
        './services/interfaces/Comtrol/adComtrolChargeCodeMappingSrv.js',
        './services/interfaces/Comtrol/adComtrolGenericMappingSrv.js',
        './services/interfaces/Comtrol/adComtrolRevenueCenterSrv.js',
        './services/interfaces/Comtrol/adComtrolRoomMappingSrv.js',
        './services/interfaces/GoMomentIvy/adGoMomentIvySetupSrv.js',
        './services/interfaces/ideas/adIdeasSetupSrv.js',
        './services/interfaces/Logs/ADInterfacesLogsSrv.js',
        './services/interfaces/M3BackOffice/ADM3SetupSrv.js',
        './services/interfaces/Monitor/ADInterfaceMonitorSrv.js',
        './services/interfaces/monsciergeSetup/adMonsciergeSetupSrv.js',
        './services/interfaces/snapShot/adSnapShotSetupSrv.js',
        './services/languages/adLanguagesSrv.js',
        './services/lightspeedPOS/adLightSpeedPOSSetupSrv.js',
        './services/notifications/adNotificationsSrv.js',
        './services/rate_configurator/adRatesAddDetailsSrv.js',
        './services/rate_configurator/adRatesAddRoomTypeSrv.js',
        './services/rate_configurator/adRatesConfigureSrv.js',
        './services/rate_configurator/adRatesRangeSrv.js',
        './services/rates/adPromotionsSrv.js',
        './services/reports/adReportsFilterSrv.js',
        './services/reports/adReportsSortOptionsSrv.js',
        './services/reports/adReportsSrv.js',
        './services/serviceProviders/adServiceProviderSrv.js',
        './services/sntAppServices/adAppVersionsSrv.js',
        './services/tools/adTelnetInterfaceSrv.js',
        './services/tools/ADToolsSrv.js',
        './services/translation/adTranslationSrv.js',
        './services/upsellAddons/adUpsellAddonSrv.js',
        './services/webhook/ADWebhookSrv.js',
        './services/WindsurferCRS/adWindsurferCRSSetupSrv.js',
        './services/zestEmailTemplates/adZestEmailTemplateSrv.js',
        './services/zestSetup/adCountrySortSrv.js',
        './services/zestSetup/adZestCheckinCheckoutSrv.js',
        './services/zestSetup/adZestMobileAppMarketingSrv.js',
        './services/zestSetup/adZestStatinAddonsSrv.js',
        './services/zestSetup/adZestStationLanguageConfigSrv.js',
        './services/zestSetup/adZestWebAddonSrv.js',
        './services/zestSetup/adZestWebRoomReadyEmailSetupSrv.js',

        './filters/highlightWordsFilter.js',

        '../shared/directives/uiColorpicker/uiColorpicker.js',
        '../shared/directives/onScroll/onScroll.js',
        '../shared/directives/limitInputRange/limitInputRange.js',
        './constants/interfaces/comtrol/adComtrolConfig.js'

    ],


    // list of files / patterns to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
        //'../payment/**/*.js': ['babel'],
        './controllers/**/*.js': ['babel'],
        './services/**/*.js': ['babel']
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['PhantomJS'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  });
};
