sntRover.constant('RVCustomExportFilterParamsConst', {
	'BOOKING_ORIGIN_CODE': 'BOOKING_ORIGIN_CODE',
	'MARKET_CODE': 'MARKET_CODE',
	'RESERVATION_STATUS': 'RESERVATION_STATUS',
	'ROOM_TYPE': 'ROOM_TYPE',
	'SEGMENT_CODE': 'SEGMENT_CODE',
	'SOURCE_CODE': 'SOURCE_CODE',
	'ACTIVE': 'ACTIVE',
	'DAYUSE INDICATOR': 'DAYUSE INDICATOR',
	'ROOM_NO': 'ROOM_NO'
});