angular.module('reportsModule')
    .constant('RVReportParamsConst', {
    	'FROM_DATE'            : 'from_date',
        'TO_DATE'              : 'to_date',
        'CANCEL_FROM_DATE'     : 'cancel_from_date',
        'CANCEL_TO_DATE'       : 'cancel_to_date',
        'ARRIVAL_FROM_DATE'    : 'arrival_from_date',
        'ARRIVAL_TO_DATE'      : 'arrival_to_date',
        'GROUP_START_DATE'     : 'group_from_date',
        'GROUP_END_DATE'       : 'group_to_date',
        'DEPOSIT_FROM_DATE'    : 'deposit_from_date',
        'DEPOSIT_TO_DATE'      : 'deposit_to_date',
        'PAID_FROM_DATE'       : 'paid_from_date',
        'PAID_TO_DATE'         : 'paid_to_date',
        'CREATE_FROM_DATE'     : 'create_from_date',
        'CREATE_TO_DATE'       : 'create_to_date',
        'ADJUSTMENT_FROM_DATE' : 'from_date',
        'ADJUSTMENT_TO_DATE'   : 'to_date',
        'SINGLE_DATE'          : 'date',

        'FROM_TIME' : 'from_time',
        'TO_TIME'   : 'to_time',

        'CHECKED_IN'  : 'checked_in',
        'CHECKED_OUT' : 'checked_out',

        'SORT_FIELD' : 'sort_field',
        'SORT_DIR'   : 'sort_dir',

        'GROUP_BY_DATE'       : 'group_by_date',
        'GROUP_BY_USER'       : 'group_by_user',
        'GROUP_BY_GROUP_NAME' : 'group_by_group_name',
        'ADDON_GROUP_BY'      : 'group_field',
        'CHARGE_TYPE'         : 'group_by_charge_type',

        'USER_IDS'               : 'user_ids',
        'MARKET_IDS'             : 'market_ids',
        'SOURCE_IDS'             : 'source_ids',
        'BOOKING_ORIGIN_IDS'     : 'booking_origin_ids',
        'INCLUDE_GUARANTEE_TYPE' : 'include_guarantee_type',
        'CHARGE_GROUP_IDS'       : 'charge_group_ids',
        'CHARGE_CODE_IDS'        : 'charge_code_ids',
        'HOLD_STATUS_IDS'        : 'hold_status_ids',
        'ADDONS_GROUPS_IDS'      : 'addon_group_ids',
        'ADDONS_IDS'             : 'addon_ids',
        'RESERVATION_STATUS'     : 'status_ids',
        'RESERVATION_ADDONS'     : 'addon_ids',
        'RATE_IDS'               : 'rate_ids',
        'RATE_TYPE_IDS'          : 'rate_type_ids',
        'RESTRICTION_IDS'        : 'restriction_ids',
        'ROOM_TYPE_IDS'          : 'room_type_ids',
        'RATE_ID'                : 'rate_id',
        'ORIGIN_VALUES'          : 'origin',
        'ORIGIN_URLS'            : 'urls'
    });