angular.module('reportsModule')
	.constant('RVReportNamesConst', {
		'CHECK_IN_CHECK_OUT'           : 'Check In / Check Out',
		'UPSELL'                       : 'Upsell',
		'WEB_CHECK_OUT_CONVERSION'     : 'Web Check Out Conversion',
		'WEB_CHECK_IN_CONVERSION'      : 'Web Check In Conversion',
		'WEB_CHECK_IN_CONV_BY_DAY'     : 'Web Check In Conversion By Day',
		'LATE_CHECK_OUT'               : 'Late Check Out',
		'EARLY_CHECKIN'                : 'Early Check In',
		'IN_HOUSE_GUEST'               : 'In-House Guests',
		'ARRIVAL'                      : 'Arrival',
		'DEPARTURE'                    : 'Departure',
		'BOOKING_SOURCE_MARKET_REPORT' : 'Booking Source & Market Report',
		'CANCELLATION_NO_SHOW'         : 'Cancellation & No Show',
		'DEPOSIT_REPORT'               : 'Guest Deposit Report',
		'GROUP_DEPOSIT_REPORT'         : 'Group Deposit Report',
		'LOGIN_AND_OUT_ACTIVITY'       : 'Login and out Activity',
		'OCCUPANCY_REVENUE_SUMMARY'    : 'Occupancy & Revenue Summary',
		'RESERVATIONS_BY_USER'         : 'Reservations By User',
		'DAILY_TRANSACTIONS'           : 'Daily Transactions',
		'DAILY_PAYMENTS'               : 'Daily Payments',
		'FORECAST_BY_DATE'             : 'Forecast',
		'ROOMS_QUEUED'                 : 'Rooms Queued',
		'FORECAST_GUEST_GROUPS'        : 'Forecast Guests & Groups',
		'MARKET_SEGMENT_STAT_REPORT'   : 'Market Segment Statistics Report',
		'COMPARISION_BY_DATE'          : 'Comparison',
		'RATE_ADJUSTMENTS_REPORT'      : 'Rate Adjustment Report',
		'GROUP_PICKUP_REPORT'          : 'Group Pick Up Report',
		'GUEST_BALANCE_REPORT'		   : 'Guest Balance Report',
		'ADDON_FORECAST'               : 'Add-On Forecast',
		'DAILY_PRODUCTION_ROOM_TYPE'   : 'Daily Production',
		'AR_SUMMARY_REPORT'			   : 'A/R Summary Report',
		'DAILY_PRODUCTION_DEMO'		   : 'Daily Production by Demographics',
		'DAILY_PRODUCTION_RATE'		   : 'Daily Production by Rate',
		'RATE_RESTRICTION_REPORT' 	   : 'Rate & Restrictions',
		'EMAIL_CHECKIN_SUMMARY'		   : 'Email Check In Summary',
		'COMPANY_TA_TOP_PRODUCERS'     : 'Company/TA Top Producers',
		'FINANCIAL_TRANSACTIONS_ADJUSTMENT_REPORT': 'Financial Transactions - Adjustment Report',
		'CREDIT_CHECK_REPORT'          : 'Credit Check Report',
		'DEPOSIT_SUMMARY' : 'Deposit Balance Summary'
	});