sntRover.controller('RVCompanyCardCtrl', ['$scope', 'RVCompanyCardSrv', '$timeout',
	function($scope, RVCompanyCardSrv, $timeout) {
		$scope.searchMode = true;
		$scope.account_type = 'COMPANY';
		$scope.currentSelectedTab = 'cc-contact-info';

		// initialize company search fields
		$scope.companySearchIntiated = false;
		$scope.companies = [];

		var presentContactInfo = {};

		//handle tab switching in both cards
		$scope.switchTabTo = function($event, tabToSwitch) {
			$event.stopPropagation();
			$event.stopImmediatePropagation();
			if ($scope.currentSelectedTab == 'cc-contact-info' && tabToSwitch !== 'cc-contact-info') {
				if ($scope.viewState.isAddNewCard) {
					$scope.errorMessage = ["Please save Company Card first"];
				} else {
					saveContactInformation($scope.contactInformation);
					$scope.$broadcast("contractTabActive");
				}
			}
			if ($scope.currentSelectedTab == 'cc-contracts' && tabToSwitch !== 'cc-contracts') {
				$scope.$broadcast("contactTabActive");
			}
			if (!$scope.viewState.isAddNewCard) {
				$scope.currentSelectedTab = tabToSwitch;
			}
		};

		$scope.$on('companyCardAvailable', function(obj, isNew) {
			$scope.searchMode = false;
			$scope.contactInformation = $scope.companyContactInformation;
			// object holding copy of contact information
			// before save we will compare 'contactInformation' against 'presentContactInfo'
			// to check whether data changed
			$scope.currentSelectedTab = 'cc-contact-info';
			presentContactInfo = angular.copy($scope.contactInformation);
			if (isNew === true) {
				$scope.contactInformation.account_details.account_name = $scope.searchData.companyCard.companyName;
				$scope.contactInformation.address_details.city = $scope.searchData.companyCard.companyCity;
				$scope.contactInformation.account_details.company_corp_id = $scope.searchData.companyCard.companyCorpId;
			}
			$scope.$broadcast("contactTabActive");
			$timeout(function() {
				$scope.$emit('hideLoader');
			}, 1000);
		});

		$scope.$on("companyCardDetached", function() {
			$scope.searchMode = true;
		});

		$scope.$on("companySearchInitiated", function() {
			$scope.companySearchIntiated = true;
			$scope.companies = $scope.searchedCompanies;
			$scope.$broadcast("refreshCompaniesScroll");
		})

		$scope.$on("companySearchStopped", function() {
			$scope.companySearchIntiated = false;
			$scope.companies = [];
			$scope.$broadcast("refreshCompaniesScroll");
		})

		$scope.$on("newCardSelected", function(id, values) {
			$scope.searchMode = false;
			$scope.$emit('hideLoader');
		})

		/**
		 * function to handle click operation on company card, mainly used for saving
		 */
		$scope.companyCardClicked = function($event) {
			$event.stopPropagation();
			if (document.getElementById("cc-contact-info") != null && getParentWithSelector($event, document.getElementById("cc-contact-info")) && $scope.currentSelectedTab == 'cc-contact-info') {
				return;
			} else if (document.getElementById("cc-contracts") != null && getParentWithSelector($event, document.getElementById("cc-contracts")) && $scope.currentSelectedTab == 'cc-contracts') {
				return;
			} else if (!$scope.viewState.isAddNewCard && document.getElementById("company-card-header") != null && getParentWithSelector($event, document.getElementById("company-card-header"))) {
				$scope.$emit("saveContactInformation");
			}
		};

		/**
		 * recieving function for save contact with data
		 */
		$scope.$on("saveContactInformation", function(event) {
			event.preventDefault();
			event.stopPropagation();
			saveContactInformation($scope.contactInformation);
		});

		$scope.$on("saveCompanyContactInformation", function(event) {
			event.preventDefault();
			saveContactInformation($scope.contactInformation);
		});

		/**
		 * a reciever function to do operation on outside click, which is generated by outside click directive
		 */
		$scope.$on("OUTSIDECLICKED", function(event, targetElement) {
			event.preventDefault();
			saveContactInformation($scope.contactInformation);
			$scope.checkOutsideClick(targetElement);
		});

		/**
		 * success callback of save contact data
		 */
		var successCallbackOfContactSaveData = function(data) {
			$scope.$emit("hideLoader");
			$scope.reservationDetails.companyCard.id = data.id;
			$scope.contactInformation.id = data.id;
			//New Card Handler
			if ($scope.viewState.isAddNewCard && typeof data.id != "undefined") {
				if ($scope.viewState.identifier == "STAY_CARD") {
					$scope.viewState.pendingRemoval.status = false;
					$scope.viewState.pendingRemoval.cardType = "";
					$scope.replaceCard('company', {
						id: data.id
					}, false);
				}
				$scope.viewState.isAddNewCard = false;
				$scope.cardSaved();
				$scope.reservationDetails.companyCard.id = data.id;
				if ($scope.reservationData && $scope.reservationData.company) {
					$scope.reservationData.company.id = data.id;
					$scope.reservationData.company.name = $scope.contactInformation.account_details.account_name;
				}
			}

			//taking a deep copy of copy of contact info. for handling save operation
			//we are not associating with scope in order to avoid watch
			presentContactInfo = angular.copy($scope.contactInformation);
		};

		$scope.clickedSaveCard = function(cardType) {
			saveContactInformation($scope.contactInformation);
		}

		/**
		 * failure callback of save contact data
		 */
		var failureCallbackOfContactSaveData = function(errorMessage) {
			$scope.$emit("hideLoader");
			$scope.errorMessage = errorMessage;
			$scope.currentSelectedTab = 'cc-contact-info';
		};

		/**
		 * function used to save the contact data, it will save only if there is any
		 * change found in the present contact info.
		 */
		var saveContactInformation = function(data) {
			var dataUpdated = false;
			if (!angular.equals(data, presentContactInfo)) {
				dataUpdated = true;
			}
			if (typeof data != 'undefined' && (dataUpdated || $scope.viewState.isAddNewCard)) {
				var dataToSend = JSON.parse(JSON.stringify(data));
				for (key in dataToSend) {
					if (typeof dataToSend[key] !== "undefined" && data[key] != null && data[key] != "") {
						//in add case's first api call, presentContactInfo will be empty object					
						if (JSON.stringify(presentContactInfo) !== '{}') {
							for (subDictKey in dataToSend[key]) {
								if (typeof dataToSend[key][subDictKey] === 'undefined' || dataToSend[key][subDictKey] === presentContactInfo[key][subDictKey]) {
									delete dataToSend[key][subDictKey];
								}
							}
						}
					} else {
						delete dataToSend[key];
					}
				}
				if (typeof dataToSend.countries !== 'undefined') {
					delete dataToSend['countries'];
				}
				dataToSend.account_type = $scope.account_type;
				$scope.invokeApi(RVCompanyCardSrv.saveContactInformation, dataToSend, successCallbackOfContactSaveData, failureCallbackOfContactSaveData);
			}
		};

	}
]);

sntRover.controller('companyResults', ['$scope', '$timeout',
	function($scope, $timeout) {
		$scope.$parent.myScrollOptions = {
			'companyResultScroll': {
				snap: false,
				scrollbars: true,
				vScroll: true,
				vScrollbar: true,
				hideScrollbar: false
			}
		}
		$scope.$on("refreshCompaniesScroll", function() {
			$timeout(function() {
				$scope.$parent.myScroll['companyResultScroll'].refresh();
			}, 500);
		})
	}
]);